apiVersion: v1
kind: Secret
metadata:
  name: amfit-secrets
  namespace: amfit
  labels:
    app.kubernetes.io/name: "amfit"
    app.kubernetes.io/component: "config"
    app.kubernetes.io/managed-by: "argocd"
    environment: "dev"
    lab_id: "lab-k8s-01"
    lab_owner: "jose.mussauer"
type: Opaque
stringData:
  pg-password: "amfit123!"
  redis-password: "redis123!"
  minio-access-key: "amfit-minio"
  minio-secret-key: "amfit-minio-secret"
  # Substituir pelo PEM da chave RS256 codificado em base64 antes de aplicar em produção
  jwt-private-key: "REPLACE_WITH_BASE64_ENCODED_PEM"
